name: Deploy to Azure via FTP
on:
  push:
    branches:
      - main   # 👈 cámbialo si usas otra rama

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    environment: Production   # 👈 esto hace disponibles tus secrets
 
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./
        server-dir: ${{ secrets.FTP_DIR }}   # 👈 carpeta destino en Azure
        exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/dumps/**
            **/.DS_Store
            **/.env*