name: Deploy to Azure via FTP
on:
  push:
    branches:
      - main   # 👈 cámbialo si usas otra rama

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    environment: Production   # 👈 esto hace disponibles tus secrets
 
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: FTPS Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./
        server-dir: /site/wwwroot/testApi/