name: Deploy to Azure via FTP
on:
  push:
    branches:
      - main   # 👈 cámbialo si usas otra rama

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    environment: Production   # 👈 esto hace disponibles tus secrets
 
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: ./
        remote_path: /site/wwwroot
        sftp_only: true
        sftpArgs: "-o ConnectTimeout=5 -o StrictHostKeyChecking=no"